name: 'Workflow1'
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main              
jobs:
  JOBA:
    runs-on: ubuntu-latest
    steps:
      - name: 'Step-1'
        run: echo 'Hello World from step-1'      
              


