name: 'my first workflow'
on:
    push:
        branches:
            - main
            - dev
    pull_request:
        branches:
            - main
env:
    APPLICATION: docker                    
jobs:      
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: 'Git checkout'
              uses: actions/checkout@v4
            - name: 'Install Docker program'
              run: sudo apt-get install ${{env.APPLICATION}} -y  
            - name: 'Install Cowsay program'
              run: sudo apt-get install cowsay -y
            - name: Create directory (Cowsay Dragon) 
              run: mkdir -p cowsay-dragon
            - name: Create diretory  (Cowsay Tux)
              run: mkdir -p cowsay-tux
            - name: Execute Cowsay CMD Tiger
              working-directory: cowsay-dragon
              run: cowsay -f dragon 'Run for cover, I am a dragon' >> dragon.txt
            - name: Execute Cowsay CMD Lion
              working-directory: cowsay-tux
              run: cowsay -f tux 'Run for cover, I am a Tux'  >> tux.txt
            - name: 'Upload the artificat to be usedby 2_job'
              uses: actions/upload-artifact@v4
              with:
                name: 'Cowsayfiles'
                path: |
                    cowsay-dragon
                    cowsay-tux 
    secon_job:
        runs-on: ubuntu-latest
        needs: first_job
        steps:
            - name: Download the artifact from 1_job
              uses: actions/download-artifact@v4
              with:
                name: 'Cowsayfiles'
            - name: Display the structure of Downloadeed files
              run: ls -R
            - name: 'Display both the files'
              run: |
                  cat cowsay-dragon/dragon.txt
                  cat cowsay-tux/tux.txt  
              
        
                
